### ISSUE TITLE
OLED Image Scale Issue

### ISSUE THREAD

**Issue by MrBull-STR** [CountDeMonet/Arduino_PKE_Meter#2]
SEE Photo for reference.
The image appears
![PKE_Image_STRB](https://user-images.githubusercontent.com/51517029/59556540-54eecc80-8f81-11e9-9d86-37059d765e62.jpg)
 to be scaled to fit another screen than 128x64.

**Comment by CountDeMonet** [comment]
a user on gbfans is having the same issue. Are you using the library version that I have in the git repo here?

https://github.com/CountDeMonet/Arduino_PKE_Meter/tree/master/Arduino/libraries

The user on gbfans bought this led screen which the company seems to have designed their own library for. The docs say it works with the lib I use but who knows. 

https://www.amazon.ca/gp/product/B01N78FUH7/ref=ppx_yo_dt_b_asin_title_o05_s00?ie=UTF8&psc=1

You may have to use their libs for things to work correctly. Try the adafruit example included in the arduino ide for the SSD1306

File -> Exampes -> Adadfruit SSD1306 -> ssd1306_128x64_ic2 

if that one doesn't work properly then you'll have to do some work to figure out what's going on

**Comment by CountDeMonet** [comment]
Seems this is coming up more often. DIYMall has a version of this display that appears to have a different resolution so some modifications and possibly use their library version are needed for it to work.

This is from a doc linked from the diymall website

http://www.diymalls.com/IIC-OLED-SSD1306
https://drive.google.com/file/d/1qkexPET5MUICAarGOtlnQk4F-JEKkrHZ/view

that document zip contains special versions of the adafruit libs
For 0.96 inch: 0.96 inch use SSD1306 drive chip. Copy "Adafruit_SSD1306.h" and 
"Adafruit_GFX.h" into "x:\arduino-1.X.X\libraries". 
In order to reduce the pins’ number, we use a hardware RESET system. So the 
standard library form Adafruit or u8glib may not very suitable. Make sure you are 
using our provided libraries, It’s very important. If those files already in you 
libraries, replace it.
They also note
The dot matrix is 128 * 32 
We never produced any 0.96 or 1.3 inch with 128*32 dot matrix. Open 
“Adafruit_SSD1306.h”, and make sure the “#define SSD1306_128_64” is available.
Could be why you are seeing some strange things.
